# Generated by Django 4.1.5 on 2023-01-19 20:22

import autoslug.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('ec302701-81f9-4272-894e-110f445dc6f7'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, null=True, populate_from=models.CharField(max_length=255, null=True), unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('ec302701-81f9-4272-894e-110f445dc6f7'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, null=True, populate_from=models.CharField(max_length=255, null=True), unique=True)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], default='M', max_length=255, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='store.category')),
            ],
            options={
                'verbose_name': 'Sub Category',
                'verbose_name_plural': 'Sub Categories',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('ec302701-81f9-4272-894e-110f445dc6f7'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, null=True, populate_from=models.CharField(max_length=255, null=True), unique=True)),
                ('product_main_image', models.ImageField(default='assets/img/default.jpg', null=True, upload_to='media')),
                ('second_product_image', models.ImageField(blank=True, default='assets/img/default.jpg', null=True, upload_to='media')),
                ('third_product_image', models.ImageField(blank=True, default='assets/img/default.jpg', null=True, upload_to='media')),
                ('fourth_product_image', models.ImageField(blank=True, default='assets/img/default.jpg', null=True, upload_to='media')),
                ('fifth_product_image', models.ImageField(blank=True, default='assets/img/default.jpg', null=True, upload_to='media')),
                ('description', models.TextField(null=True)),
                ('available_color', models.CharField(blank=True, max_length=400, null=True)),
                ('specifications', models.TextField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('sizes', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default='S', max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.PositiveIntegerField(default=0, null=True)),
                ('featured', models.BooleanField(default=False, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.subcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
