# Generated by Django 4.1.5 on 2023-01-19 20:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e79f5b1c-f4c9-43c5-8c1c-48f3c0ea9172'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e79f5b1c-f4c9-43c5-8c1c-48f3c0ea9172'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e79f5b1c-f4c9-43c5-8c1c-48f3c0ea9172'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
