# Generated by Django 4.0.5 on 2022-06-21 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=1)),
                ('sale', models.CharField(choices=[('S', 'Sports'), ('L', 'Luxury')], default=None, max_length=5)),
                ('product', models.CharField(choices=[('B', 'Bags'), ('S', 'Sweather'), ('SG', 'Sunglass')], default=None, max_length=5)),
                ('featured_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
