# Generated by Django 4.1.5 on 2023-01-19 20:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created', 'name']},
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0825f0c5-3009-4535-ad20-bacd82824281'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0825f0c5-3009-4535-ad20-bacd82824281'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0825f0c5-3009-4535-ad20-bacd82824281'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
