# Generated by Django 4.0.5 on 2022-06-21 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_category_featured_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='featured_product',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='store.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='featured_product',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='category',
            name='product',
            field=models.CharField(blank=True, choices=[('B', 'Bags'), ('S', 'Sweather'), ('SG', 'Sunglass')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='category',
            name='sale',
            field=models.CharField(blank=True, choices=[('S', 'Sports'), ('L', 'Luxury')], default='', max_length=5),
        ),
    ]
