# Generated by Django 4.0.5 on 2022-06-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_category_featured_product_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='gender',
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('A', 'All'), ('M', 'Male'), ('F', 'Female')], default='', max_length=1),
        ),
    ]
