# Generated by Django 4.1.5 on 2023-01-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_category_id_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='gender',
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('A', 'ALL'), ('M', 'MALE'), ('F', 'FEMALE')], default='M', max_length=255, null=True),
        ),
    ]
