# Generated by Django 4.0.5 on 2022-06-22 12:58

from django.db import migrations, models
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_category_gender_product_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='store/images', validators=[store.validators.validate_file_size])),
            ],
        ),
    ]
