# Generated by Django 4.1.5 on 2023-01-20 15:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_size_alter_category_options_remove_product_sizes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_color',
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('A', 'ALL'), ('M', 'MALE'), ('F', 'FEMALE')], default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='available_color',
            field=models.ManyToManyField(blank=True, to='store.color'),
        ),
    ]
