# Generated by Django 4.1.5 on 2023-01-22 16:41

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_fifth_product_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='product',
            name='product_main_image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=''),
        ),
    ]
