# Generated by Django 4.1.5 on 2023-01-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_product_fifth_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('A', 'ALL'), ('M', 'MALE'), ('F', 'FEMALE')], default='A', max_length=255, null=True),
        ),
    ]
