# Generated by Django 4.1.5 on 2023-01-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_remove_newsletter_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
