# Generated by Django 4.1.5 on 2023-01-30 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
