# Generated by Django 4.1.5 on 2023-01-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_alter_contact_updated_alter_newsletter_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
